// Banco de cartas curado para jugar en grupo.
// Criterio: sacamos anime y cosas muy de nicho, duplicados (mismo título en
// español y en inglés) y jerga técnica difícil de mimicar. Queda lo mainstream.
export const CARD_BANK = {
  "Películas/Series": [
    "El Padrino","El Padrino II","Titanic","Matrix","Inception","Interstellar","Joker","Gladiador",
    "Pulp Fiction","El Club de la Pelea","Breaking Bad","Dark","Stranger Things","La Casa de Papel",
    "Game of Thrones","Black Mirror","Better Call Saul","The Office","Peaky Blinders","Chernobyl",
    "Oppenheimer","Parásitos","Whiplash","La La Land","Se7en","El Silencio de los Inocentes",
    "Blade Runner","Memento","Psicosis","El Resplandor","Alien","Terminator","Jurassic Park",
    "Volver al Futuro","Star Wars","El Señor de los Anillos","Harry Potter","Shrek","Toy Story",
    "El Rey León","Forrest Gump","La Naranja Mecánica","2001: Odisea del Espacio","The Truman Show",
    "Her","Shutter Island","El Cisne Negro","El Pianista","Bastardos sin gloria","Django",
    "El Gran Lebowski","El Lobo de Wall Street","Scarface","Casino","Taxi Driver","El Sexto Sentido",
    "Los Sospechosos de Siempre","Apocalypse Now","Birdman","No Country for Old Men","Fargo",
    "True Detective","House of Cards","Narcos","Los Simuladores","El Marginal","The Boys",
    "Rick and Morty","BoJack Horseman",

    "Sueño de Fuga","Buenos Muchachos","Los Infiltrados","El Irlandés","Psicópata Americano",
    "El Gran Truco","Batman: El Caballero de la Noche","Batman Inicia","Logan","Deadpool",
    "Los Vengadores","Iron Man","Doctor Strange","Guardianes de la Galaxia","Pantera Negra","Dune",
    "La Llegada","Ex Machina","El Marciano","Gravedad","Mad Max: Furia en el Camino","John Wick",
    "Búsqueda Implacable","Duro de Matar","La Red Social","El Juego de la Fortuna","La Gran Apuesta",
    "Atrápame si Puedes","El Curioso Caso de Benjamin Button","El Renacido","Los 8 más Odiados",
    "Había una vez en Hollywood","Kill Bill","Perros de la Calle","El Gran Hotel Budapest",
    "The Last of Us","The Mandalorian","Los Soprano","Mad Men","The Wire","Succession","The Crown",
    "Sherlock","Loki","WandaVision","Gambito de Dama","Ozark","Vikingos","The Walking Dead","Lost",
    "Los Simpson","South Park","Friends","How I Met Your Mother","Modern Family","Brooklyn Nine-Nine",
    "Seinfeld","Parks and Recreation",

    // Dificultad media: conocidas, pero no las primeras que salen
    "El Exorcista","Tiburón","Rocky","Rambo","Los Cazafantasmas","Náufrago","Gran Torino",
    "Perfume de Mujer","Mi Pobre Angelito","Ghost: La Sombra del Amor","La Vida es Bella","Rain Man",
    "E.T.","Indiana Jones","Karate Kid","Los Goonies","Gremlins","Jumanji","La Máscara","Ace Ventura",
    "Papá por Siempre","Los Otros","El Aro","Halloween","Viernes 13","Pesadilla en Elm Street","Chucky",
    "It","El Conjuro","Scream","Depredador","Robocop","Terminator 2","Los Increíbles","Buscando a Nemo",
    "Up","Coco","Ratatouille","WALL-E","Monsters Inc.","Intensamente","La Era de Hielo","Kung Fu Panda",
    "Mi Villano Favorito","Madagascar","Dr. House","CSI","Prison Break","Suits","Grey's Anatomy",
    "The Big Bang Theory","Malcolm el de en Medio","El Chavo del 8","Los Locos Addams","MacGyver",
    "Expedientes X","Baywatch","Okupas","Graduados","Rebelde Way","Chiquititas","Floricienta",
    "Showmatch","Peter Capusotto y sus Videos","El Secreto de sus Ojos","Relatos Salvajes","Nueve Reinas",
    "Esperando la Carroza","El Clan"
  ],

  "Deportes/Deportistas": [
    "Lionel Messi","Diego Maradona","Cristiano Ronaldo","Pelé","Ronaldinho","Zinedine Zidane","Mbappé",
    "Neymar","Manu Ginóbili","Michael Jordan","LeBron James","Kobe Bryant","Stephen Curry","Usain Bolt",
    "Michael Phelps","Serena Williams","Roger Federer","Rafael Nadal","Novak Djokovic","Ayrton Senna",
    "Lewis Hamilton","Max Verstappen","Muhammad Ali","Mike Tyson","Conor McGregor","Garry Kasparov",
    "Magnus Carlsen","Diego Simeone","Pep Guardiola","Marcelo Gallardo","Carlos Bilardo",
    "Franco Colapinto","Juan Manuel Fangio","Boca Juniors","River Plate","Barcelona","Real Madrid",
    "Champions League","Copa Libertadores","Mundial","Juegos Olímpicos","VAR","Hat-trick",
    "Fuera de juego","Draft","All Star","Playoffs","Superclásico","Copa Davis","Grand Slam","NBA",
    "NFL","MLB","UFC","Rugby","Tenis","Básquet","Fútbol","Fórmula 1","Maratón","Triatlón","Ironman",
    "Tour de France","Balón de Oro","Anillo de campeón","Récord mundial","Tiempo suplementario",

    "Ángel Di María","Sergio Agüero","Dibu Martínez","Carlos Tévez","Javier Zanetti",
    "Gabriel Batistuta","Juan Román Riquelme","Martín Palermo","Lionel Scaloni",
    "Juan Sebastián Verón","Pablo Aimar","Erling Haaland","Kevin De Bruyne","Luka Modrić","Toni Kroos",
    "Karim Benzema","Mohamed Salah","Sadio Mané","Virgil van Dijk","Robert Lewandowski","Kaká",
    "Ronaldo Nazário","Andrés Iniesta","Xavi","Sergio Ramos","Iker Casillas","Diego Forlán",
    "Luis Suárez","Edinson Cavani","Diego Godín","Michael Schumacher","Fernando Alonso",
    "Sebastian Vettel","Niki Lauda","Kimi Räikkönen","Valentino Rossi","Marc Márquez","Tom Brady",
    "Tiger Woods","Diego Schwartzman","Juan Martín del Potro","Andy Murray","Simone Biles",
    "Canelo Álvarez","Floyd Mayweather","Manny Pacquiao","Ronda Rousey","Khabib Nurmagomedov",
    "NBA Finals","Super Bowl","Copa América","Eurocopa","Copa del Rey","Premier League","Serie A",
    "Bundesliga","Ligue 1","Rally Dakar","MotoGP","ATP","Penales","Tiempo de descuento",
    "Tarjeta roja","Tarjeta amarilla","Tiki-taka","Knockout","Corner","Grand Prix","Pole position",

    // Dificultad media: jugadas, roles y figuras que se actúan bien
    "Arquero","Delantero","Defensor","Mediocampista","Árbitro","Juez de línea","Banco de suplentes",
    "Director técnico","Capitán","Hinchada","Camiseta","Botines","Guantes de arquero","Silbato",
    "Cronómetro","Podio","Medalla de oro","Antorcha olímpica","Vuelta olímpica","Fichaje","Descenso",
    "Ascenso","Tabla de posiciones","Amistoso","Repechaje","Octavos de final","Cuartos de final",
    "Semifinal","Definición por penales","Autogol","Chilena","Rabona","Caño","Sombrero","Gambeta",
    "Palomita","Vaselina","Volea","Cabezazo","Tiro libre","Saque de arco","Lateral","Falta","Expulsión",
    "Antidoping","Camilla","Utilero","Estadio","Tribuna","Platea","Vestuario","Pretemporada",
    "Luis Scola","Facundo Campazzo","Paula Pareto","Las Leonas","Los Pumas","Luciana Aymar",
    "Guillermo Vilas","Gabriela Sabatini","Carlos Monzón","Marcelo Bielsa","César Luis Menotti",
    "Alfredo Di Stéfano","Mario Kempes","Daniel Passarella","Oscar Ruggeri","Fernando Redondo",
    "Hernán Crespo","Gonzalo Higuaín","Rodrigo De Paul","Enzo Fernández","Julián Álvarez",
    "Alexis Mac Allister","Cuti Romero","Nicolás Otamendi"
  ],

  "Música/Cantantes": [
    "Freddie Mercury","Queen","The Beatles","John Lennon","Paul McCartney","Michael Jackson","Madonna",
    "David Bowie","Prince","Elvis Presley","Pink Floyd","Led Zeppelin","U2","Radiohead","Coldplay",
    "Nirvana","Kurt Cobain","Metallica","AC/DC","Guns N' Roses","Axl Rose","Eminem","Kanye West",
    "Jay-Z","Drake","Taylor Swift","Adele","Beyoncé","Rihanna","The Weeknd","Bruno Mars","Ed Sheeran",
    "Shakira","Bad Bunny","Daddy Yankee","Luis Miguel","Charly García","Spinetta","Gustavo Cerati",
    "Fito Páez","Andrés Calamaro","Soda Stereo","Los Redondos","La Renga","Babasonicos",
    "Astor Piazzolla","Carlos Gardel","Mercedes Sosa","Bob Dylan","Jimi Hendrix","Eric Clapton",
    "Santana","Mozart","Beethoven","Bach","Vivaldi","Ópera","Sinfonía","Concierto","Vinilo","Grammy",
    "Billboard","MTV","Autotune","Funk","Jazz","Blues","Rock nacional","Trap","Reggaetón","Indie",
    "Electrónica",

    "The Rolling Stones","Mick Jagger","Keith Richards","The Who","Roger Waters","Black Sabbath",
    "Ozzy Osbourne","Iron Maiden","Slipknot","System of a Down","Linkin Park","Chester Bennington",
    "Red Hot Chili Peppers","Foo Fighters","Dave Grohl","Pearl Jam","Green Day","Blink-182",
    "Arctic Monkeys","The Strokes","Muse","Daft Punk","Calvin Harris","David Guetta","Avicii",
    "Billie Eilish","Lady Gaga","Katy Perry","Dua Lipa","Harry Styles","Post Malone","Travis Scott",
    "Lil Wayne","Kendrick Lamar","Karol G","Tini","Nicki Nicole","Wos","Duki","Bizarrap",
    "Rauw Alejandro","J Balvin","Ozuna","Maluma","Ennio Morricone","Hans Zimmer","John Williams",
    "Pavarotti","Plácido Domingo","Andrea Bocelli","Chopin","Tchaikovsky","Melodía","Ritmo",
    "Guitarra eléctrica","Bajo","Batería","Teclado","Sintetizador","Coro","Orquesta","Solista",
    "Álbum","Gira","Festival","Lollapalooza","Coachella","Streaming",

    // Dificultad media: rock nacional, folklore, instrumentos y jerga de recital
    "Los Fabulosos Cadillacs","Los Auténticos Decadentes","Los Piojos","Divididos","Sumo","Luca Prodan",
    "Virus","Serú Girán","Attaque 77","Bersuit","Ratones Paranoicos","No Te Va Gustar","La Vela Puerca",
    "El Cuarteto de Nos","Miranda!","Airbag","La Mona Jiménez","Rodrigo","Los Palmeras","Gilda","Cumbia",
    "Cuarteto","Chacarera","Zamba","Malambo","Bombo legüero","Bandoneón","Acordeón","Charango","Violín",
    "Saxofón","Trompeta","Piano","Flauta","Ukelele","Maracas","Pandereta","Director de orquesta",
    "Partitura","Micrófono","Amplificador","Púa","Solo de guitarra","Riff","Estribillo","Bis","Pogo",
    "Recital","Camarín","Casete","Walkman","Serenata","Villancico","Cumpleaños feliz"
  ],

  "Argentina": [
    "Buenos Aires","Mendoza","Córdoba","Rosario","La Plata","Ushuaia","El Calafate","Bariloche",
    "Mar del Plata","Salta","Cataratas del Iguazú","Aconcagua","Patagonia","Ruta 40","Obelisco",
    "Casa Rosada","Plaza de Mayo","Congreso","La Bombonera","El Monumental","Mate","Asado","Empanadas",
    "Choripán","Fernet","Dulce de leche","Alfajor","Parrilla","Vino mendocino","Malbec","Tango",
    "Milonga","Gardel","Sarmiento","Belgrano","San Martín","Malvinas","Perito Moreno",
    "Quebrada de Humahuaca","Vaca Muerta","YPF","INDEC","AFIP","DNI","CUIT","Inflación","Dólar",
    "Colectivo","Subte","Tren","Gaucho","Estancia","Pampa","Siesta","Mate cocido","Peña","Folklore",
    "Chamamé","Selección Argentina","Scaloneta","La grieta","Conurbano","Interior","Provincia",

    "San Juan","San Luis","La Rioja","Catamarca","Tucumán","Jujuy","Chaco","Formosa","Misiones",
    "Corrientes","Entre Ríos","Santa Fe","Neuquén","Río Negro","Chubut","Santa Cruz",
    "Tierra del Fuego","Puerto Madryn","Península Valdés","Las Leñas","San Rafael","Tilcara",
    "Purmamarca","Cafayate","Villa Carlos Paz","San Martín de los Andes","Villa La Angostura",
    "El Bolsón","Avenida 9 de Julio","Teatro Colón","Recoleta","La Boca","Puerto Madero","Palermo",
    "Mercado de San Telmo","Caminito","Cabildo","Plaza San Martín","Bandera argentina","Escarapela",
    "Himno Nacional","Termo","Facturas","Medialunas","Milanesa","Provoleta","Locro","Humita",
    "Día del Amigo","Feriado puente","Cepo","Paritarias","Remís","Kiosco","Boliche","Quincho",
    "Picada","Fútbol 5","Gauchito Gil","Difunta Correa","Glaciar Perito Moreno","Cerro Fitz Roy",
    "Lago Nahuel Huapi","Lago Argentino","Viento Zonda","Fiesta de la Vendimia","Bodega",
    "Rosario Central","Newell's Old Boys","Independiente","Racing","San Lorenzo",

    // Dificultad media: íconos, costumbres, juegos de infancia y lunfardo
    "Evita","Perón","Che Guevara","Borges","Cortázar","Quino","Mafalda","Fontanarrosa",
    "Inodoro Pereyra","Les Luthiers","Tato Bores","Alberto Olmedo","Sandro","Palito Ortega",
    "Susana Giménez","Mirtha Legrand","Marcelo Tinelli","Ricardo Darín","Guillermo Francella","Bondi",
    "SUBE","Colectivero","Quiniela","Prode","Truco","Generala","Metegol","Rayuela","Mancha","Escondidas",
    "Bolita","Trompo","Barrilete","Mateada","Sobremesa","Cumpleaños de 15","Acto escolar","Guardapolvo",
    "Vacaciones de invierno","Verdulería","Almacén","Fiambrería","Panadería","Carnicería","Ferretería",
    "Feria","Laburo","Guita","Fiaca","Chamuyo","Gauchada","Pilcha","Morfar","Bardo","Quilombo","Careta"
  ],

  "Vale Todo": [
    "Tinder","Netflix","Uber","WhatsApp","Instagram","TikTok","Bitcoin","ChatGPT","Wi-Fi","Vino",
    "Cerveza","Resaca","Karaoke","After","Cumpleaños","Boda","Divorcio","Jefe tóxico",
    "Reunión","Presentación","Final de la facu","Trámite","Pasaporte","Aduana","Aeropuerto",
    "Hotel","Playa","Mate amargo","Control remoto","Aire acondicionado",
    "Microondas","Heladera","Corte de luz","Banco","Tarjeta de crédito","Cuotas",
    "Propina","Delivery",

    "Spotify","YouTube","Gmail","Google Maps","Waze","Mercado Pago","Mercado Libre","Home office",
    "Zoom","PowerPoint","Excel","PDF","QR","Pendrive","Bluetooth","Story","Reels","Meme","Spoiler",
    "Hype","Cringe","FOMO","Ghosting","Red flag","Procrastinar","Overthinking","Burnout","Ansiedad",
    "Meditación","Yoga","Gym","Rutina","Notificación","Silencio incómodo","Vergüenza ajena","Visto",
    "Dejar en leído","Banear","Stalkear","Like","Match","Unfollow","Factura","Impuesto","Multa",
    "Turno online","Fila","Mudanza","Alquiler","Expensas","Garantía","Depósito","Cartera","Billetera",
    "Buzo","Zapatillas","Peaje","Estacionamiento","Cargador","Batería baja","Modo avión",
    "Pantalla rota","Actualización","Password","Spam","Terapia","Podcast","Playlist","Auriculares",
    "Smartwatch","Smart TV","Café","Té","Helado","Pizza","Hamburguesa","Sushi",
    "Domingo de bajón","Lunes","Insomnio",

    // Dificultad media: acciones y escenas cotidianas, ideales para mímica
    "Estornudar","Bostezar","Roncar","Hipo","Cosquillas","Abrazo","Aplauso","Guiño","Selfie",
    "Videollamada","Despertador","Cepillarse los dientes","Ducha fría","Toalla","Espejo","Balanza",
    "Tijera","Cinta adhesiva","Llavero","Bufanda","Gorro de lana","Ojotas","Medias desparejas",
    "Almohada","Frazada","Ventilador","Estufa","Pava","Bombilla","Tupper","Tostadora","Licuadora",
    "Sartén","Olla","Palo de amasar","Delantal","Lavarropas","Tender la ropa","Planchar","Barrer",
    "Lavar los platos","Sacar la basura","Pasear al perro","Regar las plantas","Cortar el pasto",
    "Cambiar una lamparita","Armar un mueble","Perder las llaves","Quedarse encerrado","Tocar timbre",
    "Ascensor","Escalera mecánica","Semáforo","Bocina","Embotellamiento","Carnet de conducir","Examen",
    "Entrevista de trabajo","Currículum","Aumento de sueldo","Renunciar","Primera cita","Cita a ciegas",
    "Celos","Corazón roto"
  ],
};
