// Banco de definiciones del Rosco (estilo Pasapalabra / Iván de Pineda).
// Todas las respuestas EMPIEZAN con su letra.
//
// Cada letra tiene tres niveles con 8 opciones cada uno (24 por letra):
//   facil   -> palabras de todos los días, definición directa.
//   medio   -> hay que pensarla un poco.
//   dificil -> vocabulario más rebuscado o definición con doble sentido.
//
// Excepciones: Ñ, X y W no llegan a 8 por nivel porque el idioma no tiene
// tantas palabras que empiecen así. Cuando un nivel queda con menos de 2
// opciones, el juego completa con los niveles vecinos.

export const ROSCO_LETTERS = [
  "A","B","C","D","E","F","G","H","I","J","K","L","M",
  "N","Ñ","O","P","Q","R","S","T","U","V","W","X","Y","Z",
];

export const ROSCO_NIVELES = [
  { id: "facil", label: "😌 Fácil", desc: "Palabras de todos los días." },
  { id: "medio", label: "🙂 Medio", desc: "Hay que pensarla un poco." },
  { id: "dificil", label: "🤯 Difícil", desc: "Vocabulario más rebuscado." },
];

export const ROSCO_BANK = {
  A: {
    facil: [
      { respuesta: "Auto", pista: "Vehículo de cuatro ruedas que se maneja con un volante." },
      { respuesta: "Agua", pista: "Líquido transparente y sin sabor que se toma todos los días." },
      { respuesta: "Árbol", pista: "Planta grande de tronco leñoso y ramas." },
      { respuesta: "Avión", pista: "Vehículo con alas que vuela llevando pasajeros." },
      { respuesta: "Amigo", pista: "Persona de confianza y cariño que no es de la familia." },
      { respuesta: "Azul", pista: "Color del cielo despejado." },
      { respuesta: "Abuela", pista: "Madre de tu madre o de tu padre." },
      { respuesta: "Arena", pista: "Granitos sueltos que cubren la playa." },
    ],
    medio: [
      { respuesta: "Abeja", pista: "Insecto que fabrica miel y vive en colmenas." },
      { respuesta: "Ancla", pista: "Pieza pesada que se tira al agua para sujetar un barco." },
      { respuesta: "Almohada", pista: "Objeto blando donde se apoya la cabeza al dormir." },
      { respuesta: "Alfombra", pista: "Tejido grueso que se extiende sobre el piso." },
      { respuesta: "Ascensor", pista: "Cabina que sube y baja entre los pisos de un edificio." },
      { respuesta: "Anillo", pista: "Aro que se usa en el dedo." },
      { respuesta: "Araña", pista: "Animal de ocho patas que teje telas para cazar." },
      { respuesta: "Alacrán", pista: "Arácnido con un aguijón venenoso en la punta de la cola." },
    ],
    dificil: [
      { respuesta: "Ánfora", pista: "Vasija antigua de dos asas y cuello estrecho en la que se transportaba vino." },
      { respuesta: "Alud", pista: "Masa de nieve que se desprende de la ladera y baja arrasando con todo." },
      { respuesta: "Abismo", pista: "Profundidad tan grande que no se alcanza a ver el fondo." },
      { respuesta: "Astilla", pista: "Fragmento fino y punzante que salta de la madera." },
      { respuesta: "Atajo", pista: "Camino más corto que el habitual para llegar antes." },
      { respuesta: "Aullido", pista: "Grito largo y lastimero, el que pega el lobo de noche." },
      { respuesta: "Alféizar", pista: "Parte baja del hueco de una ventana, donde se apoyan los codos." },
      { respuesta: "Amnistía", pista: "Perdón legal que borra los delitos de todo un grupo." },
    ],
  },
  B: {
    facil: [
      { respuesta: "Barco", pista: "Embarcación que navega por el agua." },
      { respuesta: "Banana", pista: "Fruta amarilla y curva que se pela con la mano." },
      { respuesta: "Boca", pista: "Parte de la cara por donde se come y se habla." },
      { respuesta: "Bicicleta", pista: "Vehículo de dos ruedas que avanza pedaleando." },
      { respuesta: "Bebé", pista: "Persona recién nacida." },
      { respuesta: "Blanco", pista: "Color de la nieve y de las nubes de un día lindo." },
      { respuesta: "Botella", pista: "Envase de cuello angosto donde se guarda un líquido." },
      { respuesta: "Beso", pista: "Muestra de cariño que se da con los labios." },
    ],
    medio: [
      { respuesta: "Brújula", pista: "Instrumento de aguja imantada que siempre marca el norte." },
      { respuesta: "Bufanda", pista: "Prenda larga que se enrolla en el cuello para el frío." },
      { respuesta: "Bisagra", pista: "Herraje de dos piezas unidas por un eje que permite que una puerta gire." },
      { respuesta: "Bigote", pista: "Pelo que crece justo arriba del labio." },
      { respuesta: "Bosque", pista: "Terreno extenso y poblado de árboles." },
      { respuesta: "Botón", pista: "Pieza redonda que pasa por un ojal y cierra la camisa." },
      { respuesta: "Balcón", pista: "Plataforma con baranda que sobresale de la pared de un edificio." },
      { respuesta: "Buzo", pista: "El que se sumerge con tanque de oxígeno; también una prenda de abrigo." },
    ],
    dificil: [
      { respuesta: "Baluarte", pista: "Parte saliente de una fortificación; también la defensa firme de una causa." },
      { respuesta: "Bruma", pista: "Niebla ligera, sobre todo la que se levanta sobre el mar." },
      { respuesta: "Boceto", pista: "Dibujo rápido y sin terminar que sirve de guía para la obra definitiva." },
      { respuesta: "Brizna", pista: "Hebra delgadísima, como la de una hoja de pasto." },
      { respuesta: "Bochorno", pista: "Calor sofocante y húmedo; también una vergüenza muy grande." },
      { respuesta: "Bóveda", pista: "Techo curvo de piedra que cubre un espacio sin columnas en el medio." },
      { respuesta: "Berrinche", pista: "Enojo exagerado y ruidoso, típico de un chico al que le dicen que no." },
      { respuesta: "Baratija", pista: "Objeto de mucho adorno y poquísimo valor." },
    ],
  },
  C: {
    facil: [
      { respuesta: "Casa", pista: "Construcción donde vive una familia." },
      { respuesta: "Caballo", pista: "Animal que se monta y galopa." },
      { respuesta: "Cama", pista: "Mueble donde se duerme." },
      { respuesta: "Corazón", pista: "Órgano que bombea la sangre." },
      { respuesta: "Cuchara", pista: "Cubierto redondeado con el que se toma la sopa." },
      { respuesta: "Camisa", pista: "Prenda de tela con cuello y botones." },
      { respuesta: "Cielo", pista: "Lo que se ve al mirar hacia arriba durante el día." },
      { respuesta: "Café", pista: "Bebida oscura y amarga que se toma para despertarse." },
    ],
    medio: [
      { respuesta: "Cactus", pista: "Planta del desierto cubierta de espinas." },
      { respuesta: "Camaleón", pista: "Reptil que cambia de color según el entorno." },
      { respuesta: "Cometa", pista: "Cuerpo celeste que deja una cola luminosa al acercarse al Sol." },
      { respuesta: "Cascada", pista: "Caída de agua de un río desde una altura." },
      { respuesta: "Cocodrilo", pista: "Reptil de fauces enormes que acecha en los ríos." },
      { respuesta: "Candado", pista: "Cerradura suelta con un arco de metal que se engancha." },
      { respuesta: "Cicatriz", pista: "Marca que deja en la piel una herida ya curada." },
      { respuesta: "Colmena", pista: "Construcción donde vive y trabaja un enjambre de abejas." },
    ],
    dificil: [
      { respuesta: "Cauce", pista: "Lecho por donde corre un río." },
      { respuesta: "Cizaña", pista: "Mala hierba del sembrado; sembrarla significa provocar discordia." },
      { respuesta: "Cúpula", pista: "Bóveda semiesférica que corona un edificio; también la elite que dirige algo." },
      { respuesta: "Cofre", pista: "Caja resistente con tapa donde se guarda lo valioso." },
      { respuesta: "Cúspide", pista: "Punto más alto al que se puede llegar." },
      { respuesta: "Coartada", pista: "Prueba de que estabas en otro lado en el momento del delito." },
      { respuesta: "Codicia", pista: "Deseo desmedido de acumular riquezas." },
      { respuesta: "Contienda", pista: "Disputa o pelea sostenida entre dos bandos." },
    ],
  },
  D: {
    facil: [
      { respuesta: "Dedo", pista: "Cada una de las cinco partes en que termina la mano." },
      { respuesta: "Diente", pista: "Pieza blanca de la boca que sirve para masticar." },
      { respuesta: "Domingo", pista: "Último día de la semana." },
      { respuesta: "Dulce", pista: "El sabor del azúcar." },
      { respuesta: "Dinero", pista: "Lo que se entrega a cambio de lo que se compra." },
      { respuesta: "Dibujo", pista: "Imagen hecha a mano con lápiz o crayón." },
      { respuesta: "Ducha", pista: "Chorro de agua bajo el que uno se baña." },
      { respuesta: "Dado", pista: "Cubo de seis caras con puntos que se tira para jugar." },
    ],
    medio: [
      { respuesta: "Delfín", pista: "Mamífero marino muy inteligente que se comunica con silbidos." },
      { respuesta: "Diccionario", pista: "Libro que ordena las palabras junto a su significado." },
      { respuesta: "Desierto", pista: "Zona árida y arenosa donde casi nunca llueve." },
      { respuesta: "Disfraz", pista: "Ropa que uno se pone para parecer otra cosa." },
      { respuesta: "Dragón", pista: "Bestia mitológica con alas que escupe fuego." },
      { respuesta: "Diamante", pista: "Piedra preciosa transparente, la más dura de todas." },
      { respuesta: "Detective", pista: "El que investiga un caso siguiendo pistas." },
      { respuesta: "Doctor", pista: "El que atiende y cura a los enfermos." },
    ],
    dificil: [
      { respuesta: "Dique", pista: "Muro construido para contener el agua." },
      { respuesta: "Deriva", pista: "Desvío de una embarcación de su rumbo por efecto del viento o la corriente." },
      { respuesta: "Dintel", pista: "Pieza horizontal superior de una puerta que descarga el peso del muro." },
      { respuesta: "Duelo", pista: "Combate pactado entre dos; también el dolor por la pérdida de alguien." },
      { respuesta: "Destello", pista: "Resplandor breve y repentino." },
      { respuesta: "Desdén", pista: "Desprecio que se muestra con pura indiferencia." },
      { respuesta: "Diluvio", pista: "Lluvia torrencial que parece no terminar nunca." },
      { respuesta: "Dádiva", pista: "Regalo que se hace sin esperar nada a cambio." },
    ],
  },
  E: {
    facil: [
      { respuesta: "Elefante", pista: "Animal enorme de trompa larga y orejas grandes." },
      { respuesta: "Escuela", pista: "Lugar donde los chicos van a estudiar." },
      { respuesta: "Estrella", pista: "Punto de luz que se ve en el cielo de noche." },
      { respuesta: "Espalda", pista: "Parte de atrás del cuerpo, entre el cuello y la cintura." },
      { respuesta: "Escalera", pista: "Serie de escalones que sirve para subir." },
      { respuesta: "Enero", pista: "Mes con el que arranca el año y las vacaciones." },
      { respuesta: "Ensalada", pista: "Plato frío de verduras crudas mezcladas." },
      { respuesta: "Equipo", pista: "Grupo de personas que juega o trabaja en conjunto." },
    ],
    medio: [
      { respuesta: "Eclipse", pista: "Fenómeno en el que un astro tapa a otro y lo deja en sombra." },
      { respuesta: "Escoba", pista: "Utensilio de cerdas y mango largo que se usa para barrer." },
      { respuesta: "Espejo", pista: "Superficie pulida que devuelve tu propia imagen." },
      { respuesta: "Erizo", pista: "Animal pequeño cubierto de púas que se hace bollito." },
      { respuesta: "Estatua", pista: "Figura tallada o fundida que representa a una persona." },
      { respuesta: "Esqueleto", pista: "Conjunto de todos los huesos del cuerpo." },
      { respuesta: "Enchufe", pista: "Donde se conecta un aparato para que le llegue la electricidad." },
      { respuesta: "Estornudo", pista: "Expulsión brusca y ruidosa de aire por la nariz." },
    ],
    dificil: [
      { respuesta: "Enjambre", pista: "Grupo numeroso de abejas que abandona la colmena junto a su reina." },
      { respuesta: "Estribo", pista: "Pieza colgada de la montura donde el jinete apoya el pie." },
      { respuesta: "Elipse", pista: "Curva cerrada y ovalada; la forma de la órbita de los planetas." },
      { respuesta: "Émbolo", pista: "Pieza que se desliza dentro de un cilindro, como en una jeringa." },
      { respuesta: "Estampida", pista: "Huida en masa y desordenada de un grupo de animales asustados." },
      { respuesta: "Enigma", pista: "Asunto dicho de forma oscura a propósito, para que cueste descifrarlo." },
      { respuesta: "Eslabón", pista: "Cada uno de los anillos que forman una cadena." },
      { respuesta: "Éxodo", pista: "Salida masiva de un pueblo que abandona su tierra." },
    ],
  },
  F: {
    facil: [
      { respuesta: "Fuego", pista: "Lo que produce llamas y calor." },
      { respuesta: "Flor", pista: "Parte colorida de la planta que se regala en ramos." },
      { respuesta: "Fútbol", pista: "Deporte de once contra once en el que solo el arquero usa las manos." },
      { respuesta: "Frutilla", pista: "Fruta roja con puntitos que se come con crema." },
      { respuesta: "Fiesta", pista: "Reunión con música y baile para festejar algo." },
      { respuesta: "Familia", pista: "Conjunto de personas unidas por parentesco." },
      { respuesta: "Fideos", pista: "Pasta larga y fina que se hierve en agua." },
      { respuesta: "Frío", pista: "Sensación del invierno, lo contrario del calor." },
    ],
    medio: [
      { respuesta: "Faro", pista: "Torre con una luz giratoria que guía a los barcos de noche." },
      { respuesta: "Fósil", pista: "Resto de un ser vivo conservado en la roca durante millones de años." },
      { respuesta: "Fósforo", pista: "Palito con cabeza inflamable que prende al frotarlo." },
      { respuesta: "Frazada", pista: "Manta gruesa que abriga en la cama." },
      { respuesta: "Ferretería", pista: "Negocio donde se compran clavos, tornillos y herramientas." },
      { respuesta: "Fantasma", pista: "Aparición de un muerto, blanca y flotante." },
      { respuesta: "Frontera", pista: "Línea que separa un país del otro." },
      { respuesta: "Fuente", pista: "Construcción de una plaza con chorros de agua." },
    ],
    dificil: [
      { respuesta: "Fragua", pista: "Fogón donde el herrero calienta el metal hasta poder darle forma." },
      { respuesta: "Fisura", pista: "Grieta fina y alargada; también la falla oculta de algo que parecía sólido." },
      { respuesta: "Fauces", pista: "Boca abierta y amenazante de un animal feroz." },
      { respuesta: "Fervor", pista: "Entusiasmo intenso y apasionado por una causa." },
      { respuesta: "Fugaz", pista: "Que dura apenas un instante, como cierta estrella." },
      { respuesta: "Fardo", pista: "Bulto grande y apretado de mercadería atado para transportarlo." },
      { respuesta: "Follaje", pista: "Conjunto de hojas y ramas de los árboles." },
      { respuesta: "Falange", pista: "Cada uno de los huesitos que forman un dedo." },
    ],
  },
  G: {
    facil: [
      { respuesta: "Gato", pista: "Animal doméstico que maúlla." },
      { respuesta: "Globo", pista: "Bolsa de goma que se infla en los cumpleaños." },
      { respuesta: "Guitarra", pista: "Instrumento de seis cuerdas que se rasguea." },
      { respuesta: "Gallina", pista: "Ave de corral que pone huevos." },
      { respuesta: "Goma", pista: "Lo que se usa para borrar el lápiz." },
      { respuesta: "Gorra", pista: "Prenda con visera que cubre la cabeza." },
      { respuesta: "Guante", pista: "Prenda que cubre la mano dedo por dedo." },
      { respuesta: "Galleta", pista: "Masa chata y crujiente que se moja en el mate." },
    ],
    medio: [
      { respuesta: "Girasol", pista: "Flor amarilla y alta que orienta su cabeza hacia el sol." },
      { respuesta: "Guarida", pista: "Refugio escondido de un animal salvaje o de alguien que huye." },
      { respuesta: "Gemelo", pista: "Hermano nacido en el mismo parto e idéntico." },
      { respuesta: "Garganta", pista: "Conducto por donde baja la comida y sale la voz." },
      { respuesta: "Gaviota", pista: "Ave blanca y gris que chilla sobre la costa." },
      { respuesta: "Granizo", pista: "Bolitas de hielo que caen del cielo y abollan los autos." },
      { respuesta: "Gusano", pista: "Animal alargado y blando que se arrastra por la tierra." },
      { respuesta: "Galaxia", pista: "Conjunto enorme de estrellas, como la Vía Láctea." },
    ],
    dificil: [
      { respuesta: "Grieta", pista: "Abertura larga y estrecha en una pared o en el hielo; también una división social." },
      { respuesta: "Gárgola", pista: "Figura monstruosa tallada que desagua el techo de una catedral." },
      { respuesta: "Gremio", pista: "Conjunto de los que ejercen el mismo oficio y defienden sus intereses." },
      { respuesta: "Gozne", pista: "Herraje sobre el que gira la hoja de una puerta." },
      { respuesta: "Guarismo", pista: "Cada uno de los signos con los que se escriben los números." },
      { respuesta: "Gesta", pista: "Hazaña memorable de un pueblo o de un héroe." },
      { respuesta: "Grillete", pista: "Aro de hierro que se cierra en el tobillo de un preso." },
      { respuesta: "Guarnición", pista: "Lo que acompaña al plato principal; también la tropa que defiende una plaza." },
    ],
  },
  H: {
    facil: [
      { respuesta: "Hoja", pista: "Parte verde del árbol que se cae en otoño." },
      { respuesta: "Helado", pista: "Postre frío que se sirve en cucurucho." },
      { respuesta: "Hermano", pista: "Hijo de los mismos padres que vos." },
      { respuesta: "Hospital", pista: "Lugar donde se atiende a los enfermos." },
      { respuesta: "Huevo", pista: "Lo que pone la gallina y se come frito o duro." },
      { respuesta: "Hora", pista: "Período de sesenta minutos." },
      { respuesta: "Humo", pista: "Lo gris que se levanta de algo que se está quemando." },
      { respuesta: "Hielo", pista: "Agua congelada que se le pone al vaso." },
    ],
    medio: [
      { respuesta: "Hormiga", pista: "Insecto chico que vive en colonias y carga hojas mucho más grandes que él." },
      { respuesta: "Huracán", pista: "Tormenta de vientos violentos que giran alrededor de un centro." },
      { respuesta: "Herradura", pista: "Hierro en forma de U que se clava al casco del caballo y que da suerte." },
      { respuesta: "Hamaca", pista: "Asiento colgante en el que los chicos se mecen." },
      { respuesta: "Hombro", pista: "Parte del cuerpo donde el brazo se une al tronco." },
      { respuesta: "Hongo", pista: "Ser vivo con forma de sombrerito que brota en la humedad." },
      { respuesta: "Huella", pista: "Marca que deja el pie al pisar." },
      { respuesta: "Herida", pista: "Corte o lesión abierta en la piel." },
    ],
    dificil: [
      { respuesta: "Hollín", pista: "Polvo negro que el humo va dejando pegado en las paredes de una chimenea." },
      { respuesta: "Hastío", pista: "Cansancio y aburrimiento profundos ante algo repetido." },
      { respuesta: "Hito", pista: "Mojón que marca un límite; también el hecho que marca una época." },
      { respuesta: "Hazaña", pista: "Acción heroica y muy difícil de repetir." },
      { respuesta: "Hurto", pista: "Robo cometido sin violencia ni intimidación." },
      { respuesta: "Hedor", pista: "Olor pestilente e insoportable." },
      { respuesta: "Hidalgo", pista: "Noble de la vieja España, de sangre pero sin fortuna." },
      { respuesta: "Hosco", pista: "De trato áspero, seco y poco amable." },
    ],
  },
  I: {
    facil: [
      { respuesta: "Isla", pista: "Porción de tierra rodeada de agua por todos lados." },
      { respuesta: "Invierno", pista: "Estación más fría del año." },
      { respuesta: "Iglesia", pista: "Edificio donde se celebra la misa." },
      { respuesta: "Impresora", pista: "Aparato que pasa al papel lo que está en la computadora." },
      { respuesta: "Idea", pista: "Lo que se te ocurre de golpe en la cabeza." },
      { respuesta: "Imagen", pista: "Representación visual de algo." },
      { respuesta: "Insecto", pista: "Bicho de seis patas, como la mosca o el grillo." },
      { respuesta: "Izquierda", pista: "Lado opuesto al derecho, el del corazón." },
    ],
    medio: [
      { respuesta: "Iglú", pista: "Vivienda con forma de cúpula construida con bloques de hielo." },
      { respuesta: "Imán", pista: "Objeto capaz de atraer al hierro y a otros metales." },
      { respuesta: "Iceberg", pista: "Mole de hielo a la deriva que esconde bajo el agua la mayor parte de su tamaño." },
      { respuesta: "Incendio", pista: "Fuego grande y descontrolado que destruye lo que encuentra." },
      { respuesta: "Idioma", pista: "Lengua que habla un pueblo." },
      { respuesta: "Iguana", pista: "Reptil verde de cresta que se queda quieto tomando sol." },
      { respuesta: "Imperio", pista: "Conjunto de territorios sometidos a un mismo emperador." },
      { respuesta: "Isabelino", pista: "Estilo de la época de la reina Isabel de Inglaterra." },
    ],
    dificil: [
      { respuesta: "Índigo", pista: "Color azul oscuro que está entre el azul y el violeta." },
      { respuesta: "Insignia", pista: "Distintivo que se lleva encima para identificar a qué grupo pertenecés." },
      { respuesta: "Ímpetu", pista: "Fuerza y decisión con que se hace algo de golpe." },
      { respuesta: "Indicio", pista: "Señal que permite sospechar algo que todavía no se probó." },
      { respuesta: "Inercia", pista: "Tendencia de un cuerpo a seguir como está; también dejarse llevar sin decidir." },
      { respuesta: "Infamia", pista: "Deshonra pública provocada por un acto vil." },
      { respuesta: "Insomnio", pista: "Imposibilidad de conciliar el sueño por más que uno lo intente." },
      { respuesta: "Íntegro", pista: "Entero y sin que le falte nada; también el que es incorruptible." },
    ],
  },
  J: {
    facil: [
      { respuesta: "Jugo", pista: "Bebida que se obtiene exprimiendo una fruta." },
      { respuesta: "Jirafa", pista: "Animal africano de cuello larguísimo." },
      { respuesta: "Jabón", pista: "Producto que hace espuma y se usa para lavarse." },
      { respuesta: "Jardín", pista: "Terreno con plantas y flores al lado de la casa." },
      { respuesta: "Jueves", pista: "Día que va justo después del miércoles." },
      { respuesta: "Juguete", pista: "Objeto con el que juegan los chicos." },
      { respuesta: "Jefe", pista: "El que manda en un trabajo." },
      { respuesta: "Joven", pista: "El que todavía no llegó a viejo." },
    ],
    medio: [
      { respuesta: "Jaula", pista: "Caja con rejas donde se encierra a un animal." },
      { respuesta: "Jinete", pista: "El que monta a caballo y lo gobierna." },
      { respuesta: "Jeroglífico", pista: "Signo de la escritura del antiguo Egipto." },
      { respuesta: "Jarra", pista: "Recipiente con asa y pico para servir líquido." },
      { respuesta: "Jamón", pista: "Fiambre que sale de la pata del cerdo." },
      { respuesta: "Jubilado", pista: "El que dejó de trabajar y cobra por sus años de aporte." },
      { respuesta: "Jengibre", pista: "Raíz picante que se usa en infusiones y en la comida oriental." },
      { respuesta: "Jorobado", pista: "El que tiene una curvatura marcada en la espalda." },
    ],
    dificil: [
      { respuesta: "Júbilo", pista: "Alegría intensa que no se puede disimular." },
      { respuesta: "Jerga", pista: "Lenguaje propio de un oficio o de un grupo, difícil de entender desde afuera." },
      { respuesta: "Jactancia", pista: "Costumbre de alardear de lo que uno tiene o hace." },
      { respuesta: "Jauría", pista: "Conjunto de perros que persiguen a una presa en manada." },
      { respuesta: "Juramento", pista: "Promesa solemne que se hace poniendo algo sagrado por testigo." },
      { respuesta: "Jerarquía", pista: "Orden de mando que va del que más manda al que menos." },
      { respuesta: "Jaqueca", pista: "Dolor de cabeza fuerte y persistente." },
      { respuesta: "Jolgorio", pista: "Diversión ruidosa y bulliciosa." },
    ],
  },
  K: {
    facil: [
      { respuesta: "Kiosco", pista: "Puesto pequeño en la vereda donde se venden golosinas y diarios." },
      { respuesta: "Kilo", pista: "Unidad de peso equivalente a mil gramos." },
      { respuesta: "Kiwi", pista: "Fruta peluda por fuera, verde y con semillas negras por dentro." },
      { respuesta: "Karaoke", pista: "Micrófono y pantalla con la letra para cantar temas conocidos." },
      { respuesta: "Kétchup", pista: "Salsa roja de tomate que acompaña a las papas fritas." },
      { respuesta: "Kilómetro", pista: "Distancia equivalente a mil metros." },
      { respuesta: "Koala", pista: "Marsupial australiano que duerme casi todo el día y come eucalipto." },
      { respuesta: "Karate", pista: "Arte marcial japonés de golpes secos con manos y pies." },
    ],
    medio: [
      { respuesta: "Kayak", pista: "Embarcación angosta y cerrada que se impulsa con un remo de dos palas." },
      { respuesta: "Kimono", pista: "Túnica larga japonesa que se cierra cruzada con una faja ancha." },
      { respuesta: "Kinesiólogo", pista: "Profesional que rehabilita lesiones con ejercicios y masajes." },
      { respuesta: "Karma", pista: "Idea oriental de que todo lo que hacés termina volviendo." },
      { respuesta: "Kermés", pista: "Fiesta popular al aire libre con puestos y juegos." },
      { respuesta: "Kilogramo", pista: "Unidad de masa del sistema internacional." },
      { respuesta: "Kamikaze", pista: "Piloto japonés que se estrellaba a propósito; el que se arriesga sin medir." },
      { respuesta: "Kiosquero", pista: "El que atiende el puesto de golosinas y diarios." },
    ],
    dificil: [
      { respuesta: "Kerosene", pista: "Combustible derivado del petróleo que se usaba en lámparas y estufas." },
      { respuesta: "Kilometraje", pista: "Cantidad de kilómetros que lleva recorridos un vehículo." },
      { respuesta: "Kril", pista: "Camarón diminuto del que se alimentan las ballenas." },
      { respuesta: "Kéfir", pista: "Leche fermentada con hongos, parecida a un yogur bebible." },
      { respuesta: "Kilovatio", pista: "Unidad de potencia equivalente a mil watts." },
      { respuesta: "Kindergarten", pista: "Nombre alemán del jardín de infantes." },
      { respuesta: "Kurdo", pista: "Pueblo sin Estado repartido entre Turquía, Irak, Irán y Siria." },
    ],
  },
  L: {
    facil: [
      { respuesta: "Luna", pista: "Astro que se ve de noche y va cambiando de forma." },
      { respuesta: "Libro", pista: "Conjunto de hojas encuadernadas que se lee." },
      { respuesta: "León", pista: "Felino con melena al que llaman el rey de la selva." },
      { respuesta: "Leche", pista: "Líquido blanco que dan las vacas." },
      { respuesta: "Lápiz", pista: "Con lo que se escribe y después se puede borrar." },
      { respuesta: "Lluvia", pista: "Agua que cae del cielo." },
      { respuesta: "Llave", pista: "Objeto de metal con dientes que abre una cerradura." },
      { respuesta: "Lengua", pista: "Músculo de la boca con el que se saborea." },
    ],
    medio: [
      { respuesta: "Linterna", pista: "Objeto portátil que se enciende para alumbrar en la oscuridad." },
      { respuesta: "Laberinto", pista: "Construcción de pasillos enredados donde es fácil perderse." },
      { respuesta: "Lupa", pista: "Lente con mango que agranda lo que se está mirando." },
      { respuesta: "Lagartija", pista: "Reptil chiquito que corre por las paredes y se escapa." },
      { respuesta: "Langosta", pista: "Crustáceo marino de caparazón y pinzas, muy caro en el restaurante." },
      { respuesta: "Laguna", pista: "Espejo de agua más chico que un lago; también un vacío en la memoria." },
      { respuesta: "Lechuza", pista: "Ave nocturna de cara blanca y ojos enormes." },
      { respuesta: "Ladrillo", pista: "Bloque de barro cocido con el que se levanta una pared." },
    ],
    dificil: [
      { respuesta: "Legado", pista: "Lo que alguien deja al morir, sean bienes o una obra que lo sobrevive." },
      { respuesta: "Lastre", pista: "Peso que se carga para dar estabilidad; también lo que frena un avance." },
      { respuesta: "Litoral", pista: "Franja de tierra que corre pegada a la costa." },
      { respuesta: "Lucero", pista: "Astro que brilla más que el resto, sobre todo antes del amanecer." },
      { respuesta: "Letargo", pista: "Sueño profundo y prolongado; también un estado de inactividad total." },
      { respuesta: "Linaje", pista: "Línea de antepasados de la que uno desciende." },
      { respuesta: "Lóbrego", pista: "Oscuro, sombrío y tenebroso." },
      { respuesta: "Lisonja", pista: "Elogio exagerado que se dice solamente para caer bien." },
    ],
  },
  M: {
    facil: [
      { respuesta: "Mano", pista: "Parte del cuerpo que termina en cinco dedos." },
      { respuesta: "Mesa", pista: "Mueble de tabla y patas alrededor del cual se come." },
      { respuesta: "Mar", pista: "Gran masa de agua salada." },
      { respuesta: "Mamá", pista: "La que te trajo al mundo." },
      { respuesta: "Manzana", pista: "Fruta redonda, roja o verde, que se come con cáscara." },
      { respuesta: "Martes", pista: "Día que sigue al lunes." },
      { respuesta: "Mono", pista: "Animal que trepa a los árboles y se cuelga de la cola." },
      { respuesta: "Miel", pista: "Producto dulce y espeso que fabrican las abejas." },
    ],
    medio: [
      { respuesta: "Murciélago", pista: "Único mamífero que vuela y se orienta con ecos en la oscuridad." },
      { respuesta: "Momia", pista: "Cuerpo embalsamado y envuelto en vendas." },
      { respuesta: "Molino", pista: "Construcción de aspas que el viento hace girar para moler el grano." },
      { respuesta: "Mochila", pista: "Bolso con tiras que se carga sobre la espalda." },
      { respuesta: "Mariposa", pista: "Insecto de alas coloridas que antes fue oruga." },
      { respuesta: "Mosquito", pista: "Insecto que zumba en la oreja de noche y pica." },
      { respuesta: "Mandíbula", pista: "Hueso móvil de la cara donde se apoyan los dientes de abajo." },
      { respuesta: "Muralla", pista: "Muro alto y grueso que rodea y defiende una ciudad." },
    ],
    dificil: [
      { respuesta: "Mástil", pista: "Palo vertical de un barco que sostiene las velas." },
      { respuesta: "Médula", pista: "Sustancia blanda que ocupa el interior de los huesos." },
      { respuesta: "Marea", pista: "Ascenso y descenso periódico del mar por la atracción de la Luna." },
      { respuesta: "Mecha", pista: "Cordón que se enciende para que el fuego llegue hasta un explosivo." },
      { respuesta: "Mustio", pista: "Marchito y sin brillo; también alguien decaído y triste." },
      { respuesta: "Mordaza", pista: "Lo que se le pone a alguien en la boca para que no pueda hablar." },
      { respuesta: "Menester", pista: "Necesidad de hacer algo; también el oficio al que uno se dedica." },
      { respuesta: "Merodear", pista: "Dar vueltas alrededor de un lugar con intenciones sospechosas." },
    ],
  },
  N: {
    facil: [
      { respuesta: "Nariz", pista: "Parte de la cara con la que se huele." },
      { respuesta: "Nube", pista: "Masa blanca de vapor que flota en el cielo." },
      { respuesta: "Noche", pista: "Parte del día en que está oscuro." },
      { respuesta: "Nieve", pista: "Lo blanco que cae del cielo cuando hace mucho frío." },
      { respuesta: "Naranja", pista: "Fruta cítrica que le da el nombre a un color." },
      { respuesta: "Negro", pista: "Color de la oscuridad más total." },
      { respuesta: "Nene", pista: "Varón de pocos años, todavía sin edad escolar." },
      { respuesta: "Nombre", pista: "Palabra con la que te llaman desde que naciste." },
    ],
    medio: [
      { respuesta: "Nido", pista: "Construcción donde las aves ponen y empollan sus huevos." },
      { respuesta: "Niebla", pista: "Nube baja y espesa que impide ver a lo lejos." },
      { respuesta: "Náufrago", pista: "El que sobrevive al hundimiento de su barco y queda a la deriva." },
      { respuesta: "Nuez", pista: "Fruto seco de cáscara dura y arrugada que hay que romper." },
      { respuesta: "Novela", pista: "Obra literaria larga de ficción." },
      { respuesta: "Nudo", pista: "Lazo apretado difícil de desatar; también la unidad de velocidad en el mar." },
      { respuesta: "Nutria", pista: "Mamífero acuático de pelo espeso que nada panza arriba." },
      { respuesta: "Naipe", pista: "Cada una de las cartas de la baraja." },
    ],
    dificil: [
      { respuesta: "Néctar", pista: "Líquido dulce que segregan las flores y que las abejas recogen." },
      { respuesta: "Nostalgia", pista: "Tristeza por un tiempo o un lugar que quedaron atrás." },
      { respuesta: "Nómade", pista: "El que no se asienta en un lugar fijo y va mudando su campamento." },
      { respuesta: "Nervio", pista: "Fibra que lleva las señales entre el cerebro y el resto del cuerpo." },
      { respuesta: "Nimio", pista: "Tan insignificante que no vale la pena discutirlo." },
      { respuesta: "Necio", pista: "Terco que no atiende razones por más que se las expliquen." },
      { respuesta: "Nicho", pista: "Hueco abierto en una pared; también el espacio propio de un negocio." },
      { respuesta: "Naufragio", pista: "Hundimiento de una embarcación; también el fracaso total de un proyecto." },
    ],
  },
  "Ñ": {
    facil: [
      { respuesta: "Ñandú", pista: "Ave grande de la pampa que corre muy rápido y no vuela." },
      { respuesta: "Ñoquis", pista: "Pasta redonda de papa que se come los días 29." },
      { respuesta: "Ñu", pista: "Antílope africano que migra en manadas enormes por la sabana." },
    ],
    medio: [
      { respuesta: "Ñato", pista: "El que tiene la nariz corta y chata." },
      { respuesta: "Ñoño", pista: "Persona sosa, apocada y demasiado remilgada." },
      { respuesta: "Ñapa", pista: "Regalito que el vendedor agrega de yapa." },
    ],
    dificil: [
      { respuesta: "Ñoñería", pista: "Dicho o hecho propio de alguien soso y remilgado." },
      { respuesta: "Ñacurutú", pista: "Búho grande de ojos amarillos, común en el litoral argentino." },
      { respuesta: "Ñandutí", pista: "Encaje paraguayo finísimo que imita una telaraña." },
      { respuesta: "Ñire", pista: "Árbol de la Patagonia cuyas hojas se ponen rojas en otoño." },
    ],
  },
  O: {
    facil: [
      { respuesta: "Ojo", pista: "Órgano con el que se ve." },
      { respuesta: "Oso", pista: "Animal grande y peludo al que le gusta la miel." },
      { respuesta: "Oro", pista: "Metal precioso de color amarillo." },
      { respuesta: "Oreja", pista: "Parte del cuerpo con la que se escucha." },
      { respuesta: "Once", pista: "Número que sigue al diez." },
      { respuesta: "Olla", pista: "Recipiente hondo con asas para cocinar." },
      { respuesta: "Otoño", pista: "Estación en la que se caen las hojas." },
      { respuesta: "Oveja", pista: "Animal de campo del que se saca la lana." },
    ],
    medio: [
      { respuesta: "Oasis", pista: "Zona con agua y vegetación en medio del desierto." },
      { respuesta: "Ombligo", pista: "Cicatriz que queda en la panza al cortar el cordón umbilical." },
      { respuesta: "Obelisco", pista: "Monumento alto de cuatro caras que remata en punta piramidal." },
      { respuesta: "Ola", pista: "Onda de agua que viene y rompe en la orilla." },
      { respuesta: "Orquesta", pista: "Conjunto grande de músicos que toca bajo la batuta de un director." },
      { respuesta: "Ovillo", pista: "Bola de lana o hilo enrollado sobre sí mismo." },
      { respuesta: "Orquídea", pista: "Flor exótica y delicada de formas caprichosas." },
      { respuesta: "Ostra", pista: "Molusco de dos valvas dentro del cual a veces aparece una perla." },
    ],
    dificil: [
      { respuesta: "Ocaso", pista: "Momento en que el sol se esconde; también la decadencia de algo." },
      { respuesta: "Orfebre", pista: "Artesano que trabaja el oro y la plata." },
      { respuesta: "Óxido", pista: "Capa rojiza que va comiendo el hierro expuesto al aire húmedo." },
      { respuesta: "Obstinado", pista: "El que se aferra a una idea y no la suelta ni a palos." },
      { respuesta: "Ocurrencia", pista: "Idea repentina e ingeniosa que se le viene a uno a la cabeza." },
      { respuesta: "Oprobio", pista: "Deshonra pública y humillante." },
      { respuesta: "Ondear", pista: "Moverse formando ondas, como la bandera al viento." },
      { respuesta: "Oquedad", pista: "Hueco o espacio vacío dentro de un cuerpo." },
    ],
  },
  P: {
    facil: [
      { respuesta: "Perro", pista: "Animal doméstico que ladra." },
      { respuesta: "Pan", pista: "Alimento de harina que sale del horno." },
      { respuesta: "Pelota", pista: "Objeto redondo con el que se juega al fútbol." },
      { respuesta: "Pie", pista: "Parte del cuerpo con la que se camina." },
      { respuesta: "Papá", pista: "Como le decís a tu padre desde que sos chico." },
      { respuesta: "Pizza", pista: "Masa redonda con salsa y queso que va al horno." },
      { respuesta: "Puerta", pista: "Por donde se entra y se sale de una habitación." },
      { respuesta: "Playa", pista: "Orilla de arena junto al mar." },
    ],
    medio: [
      { respuesta: "Pirámide", pista: "Construcción egipcia de base cuadrada y caras triangulares." },
      { respuesta: "Paraguas", pista: "Objeto plegable que se abre para no mojarse." },
      { respuesta: "Péndulo", pista: "Peso colgado de un hilo que oscila de un lado al otro." },
      { respuesta: "Pulpo", pista: "Animal marino de ocho brazos con ventosas." },
      { respuesta: "Pingüino", pista: "Ave que no vuela, nada como pez y camina erguida sobre el hielo." },
      { respuesta: "Puente", pista: "Construcción que salva un río o una depresión para poder cruzarlos." },
      { respuesta: "Panal", pista: "Estructura de celdas hexagonales de cera que construyen las abejas." },
      { respuesta: "Pincel", pista: "Herramienta con cerdas y mango que se moja en pintura." },
    ],
    dificil: [
      { respuesta: "Pánico", pista: "Miedo súbito e incontrolable que llega a paralizar." },
      { respuesta: "Penumbra", pista: "Luz débil e incierta, la que queda entre la claridad y la oscuridad." },
      { respuesta: "Pórtico", pista: "Espacio con columnas que precede la entrada de un edificio." },
      { respuesta: "Peldaño", pista: "Cada uno de los escalones que se pisan al subir una escalera." },
      { respuesta: "Presagio", pista: "Señal que anuncia por anticipado algo que va a pasar." },
      { respuesta: "Prófugo", pista: "El que se fugó y huye de la justicia." },
      { respuesta: "Pesquisa", pista: "Investigación que se hace para averiguar algo oculto." },
      { respuesta: "Perenne", pista: "Que dura para siempre, como cierto tipo de planta." },
    ],
  },
  Q: {
    facil: [
      { respuesta: "Queso", pista: "Alimento que se obtiene cuajando la leche." },
      { respuesta: "Quince", pista: "Número que va justo después del catorce." },
      { respuesta: "Quinta", pista: "Casa de campo con parque, parrilla y pileta." },
      { respuesta: "Química", pista: "Materia del colegio donde se estudian los elementos y sus reacciones." },
      { respuesta: "Quemadura", pista: "Lesión que deja el fuego o algo muy caliente sobre la piel." },
      { respuesta: "Quieto", pista: "El que no se mueve ni un poquito." },
      { respuesta: "Quinientos", pista: "Número que se escribe con un cinco y dos ceros." },
      { respuesta: "Querer", pista: "Sentir cariño por alguien; también desear algo." },
    ],
    medio: [
      { respuesta: "Quirófano", pista: "Sala del hospital donde se realizan las operaciones." },
      { respuesta: "Quilombo", pista: "En lunfardo, un lío o desorden bien grande." },
      { respuesta: "Quijada", pista: "Hueso de la mandíbula donde se apoyan los dientes de abajo." },
      { respuesta: "Quejido", pista: "Sonido lastimero que se le escapa a quien sufre." },
      { respuesta: "Quilla", pista: "Pieza central del fondo del barco, que va de proa a popa." },
      { respuesta: "Quinteto", pista: "Grupo de cinco músicos." },
      { respuesta: "Quietud", pista: "Estado de calma absoluta y sin movimiento." },
      { respuesta: "Quebracho", pista: "Árbol del norte argentino de madera durísima." },
    ],
    dificil: [
      { respuesta: "Quimera", pista: "Ilusión imposible de alcanzar; monstruo mitológico hecho de varios animales." },
      { respuesta: "Quilate", pista: "Unidad con la que se mide la pureza del oro." },
      { respuesta: "Quijote", pista: "El que pelea por causas perdidas; el personaje de Cervantes." },
      { respuesta: "Querella", pista: "Acusación formal que se presenta ante un juez." },
      { respuesta: "Quisquilloso", pista: "El que se ofende por cualquier detalle mínimo." },
      { respuesta: "Quórum", pista: "Cantidad mínima de presentes para que una sesión sea válida." },
      { respuesta: "Quintal", pista: "Antigua unidad de peso equivalente a cien libras." },
      { respuesta: "Quimérico", pista: "Que es pura fantasía y no hay forma de lograrlo." },
    ],
  },
  R: {
    facil: [
      { respuesta: "Ratón", pista: "Animal chico y gris al que le gusta el queso." },
      { respuesta: "Río", pista: "Corriente de agua que desemboca en el mar." },
      { respuesta: "Rueda", pista: "Pieza redonda que gira y hace andar al auto." },
      { respuesta: "Rojo", pista: "Color de la sangre y de los tomates maduros." },
      { respuesta: "Reloj", pista: "Aparato que marca la hora." },
      { respuesta: "Regalo", pista: "Lo que se recibe envuelto el día del cumpleaños." },
      { respuesta: "Rey", pista: "El que gobierna un reino." },
      { respuesta: "Risa", pista: "Lo que sale sin querer cuando algo te causa gracia." },
    ],
    medio: [
      { respuesta: "Relámpago", pista: "Resplandor repentino que ilumina el cielo en plena tormenta." },
      { respuesta: "Rompecabezas", pista: "Juego de piezas que hay que encastrar para formar una imagen." },
      { respuesta: "Rodilla", pista: "Articulación que une el muslo con la pierna." },
      { respuesta: "Rana", pista: "Anfibio verde que salta y croa cerca del agua." },
      { respuesta: "Raíz", pista: "Parte de la planta que se hunde en la tierra." },
      { respuesta: "Remo", pista: "Pala larga con la que se impulsa un bote." },
      { respuesta: "Rebaño", pista: "Conjunto de ovejas que se mueve junto." },
      { respuesta: "Ruina", pista: "Resto de una construcción que el tiempo derrumbó." },
    ],
    dificil: [
      { respuesta: "Refugio", pista: "Lugar donde ponerse a salvo del peligro o del mal tiempo." },
      { respuesta: "Rencor", pista: "Resentimiento que se guarda mucho tiempo sin perdonar." },
      { respuesta: "Riendas", pista: "Correas con las que se gobierna al caballo; también el control de una situación." },
      { respuesta: "Rastro", pista: "Señal que algo deja atrás al pasar y permite seguirlo." },
      { respuesta: "Recelo", pista: "Desconfianza que se siente sin tener pruebas." },
      { respuesta: "Retahíla", pista: "Serie larga de cosas dichas una atrás de la otra sin parar." },
      { respuesta: "Rúbrica", pista: "Trazo o garabato que acompaña a la firma." },
      { respuesta: "Roña", pista: "Suciedad pegada y vieja; también tacañería." },
    ],
  },
  S: {
    facil: [
      { respuesta: "Sol", pista: "Estrella que ilumina el día." },
      { respuesta: "Silla", pista: "Mueble con respaldo donde uno se sienta." },
      { respuesta: "Sal", pista: "Condimento blanco que se le agrega a la comida." },
      { respuesta: "Sopa", pista: "Comida líquida y caliente que se toma con cuchara." },
      { respuesta: "Sábado", pista: "Día anterior al domingo." },
      { respuesta: "Sangre", pista: "Líquido rojo que corre por las venas." },
      { respuesta: "Sombrero", pista: "Prenda con ala que protege la cabeza del sol." },
      { respuesta: "Semana", pista: "Conjunto de siete días seguidos." },
    ],
    medio: [
      { respuesta: "Semáforo", pista: "Dispositivo de tres luces que ordena el tránsito." },
      { respuesta: "Sirena", pista: "Ser mitológico mitad mujer y mitad pez." },
      { respuesta: "Sombra", pista: "Silueta oscura que proyecta un cuerpo cuando le tapa la luz." },
      { respuesta: "Serpiente", pista: "Reptil sin patas que se arrastra y a veces tiene veneno." },
      { respuesta: "Sartén", pista: "Recipiente chato con mango que se usa para freír." },
      { respuesta: "Selva", pista: "Bosque tropical tan denso y húmedo que casi no deja pasar la luz." },
      { respuesta: "Sótano", pista: "Piso que queda por debajo del nivel de la calle." },
      { respuesta: "Sifón", pista: "Botella a presión de la que sale la soda." },
    ],
    dificil: [
      { respuesta: "Sigilo", pista: "Cuidado extremo para moverse sin hacer ruido y no ser descubierto." },
      { respuesta: "Sarcasmo", pista: "Burla mordaz que dice justo lo contrario de lo que quiere decir." },
      { respuesta: "Sendero", pista: "Camino angosto de tierra, abierto por el paso repetido." },
      { respuesta: "Súplica", pista: "Pedido hecho con humildad e insistencia." },
      { respuesta: "Sosiego", pista: "Calma y tranquilidad del ánimo." },
      { respuesta: "Semblante", pista: "Expresión del rostro que delata cómo está uno por dentro." },
      { respuesta: "Sortilegio", pista: "Hechizo o adivinación hecha por artes mágicas." },
      { respuesta: "Soslayo", pista: "De reojo, mirando de costado y sin dar la cara." },
    ],
  },
  T: {
    facil: [
      { respuesta: "Tren", pista: "Vehículo largo que anda sobre vías." },
      { respuesta: "Tijera", pista: "Herramienta de dos hojas cruzadas que sirve para cortar." },
      { respuesta: "Techo", pista: "Parte de arriba que cubre una casa." },
      { respuesta: "Torta", pista: "Postre redondo al que se le ponen velitas." },
      { respuesta: "Tenedor", pista: "Cubierto de puntas con el que se pincha la comida." },
      { respuesta: "Tierra", pista: "Planeta en el que vivimos; también el suelo que se pisa." },
      { respuesta: "Teléfono", pista: "Aparato con el que se habla a distancia." },
      { respuesta: "Tigre", pista: "Felino rayado de naranja y negro." },
    ],
    medio: [
      { respuesta: "Termómetro", pista: "Instrumento que sirve para medir la temperatura." },
      { respuesta: "Tornado", pista: "Columna de aire que gira a gran velocidad y toca el suelo." },
      { respuesta: "Telaraña", pista: "Red pegajosa tejida para atrapar insectos." },
      { respuesta: "Tortuga", pista: "Reptil lento que carga su caparazón a todos lados." },
      { respuesta: "Tobillo", pista: "Articulación que une el pie con la pierna." },
      { respuesta: "Trompeta", pista: "Instrumento de viento dorado de tres pistones." },
      { respuesta: "Tesoro", pista: "Riqueza escondida, típicamente enterrada dentro de un cofre." },
      { respuesta: "Tiburón", pista: "Pez grande de aleta triangular y varias filas de dientes." },
    ],
    dificil: [
      { respuesta: "Tregua", pista: "Interrupción pactada de las hostilidades, sin que la guerra termine." },
      { respuesta: "Trinchera", pista: "Zanja cavada en el frente para protegerse del fuego enemigo." },
      { respuesta: "Tímpano", pista: "Membrana del oído que vibra cuando le llega el sonido." },
      { respuesta: "Talismán", pista: "Objeto al que se le atribuye el poder de proteger a quien lo lleva." },
      { respuesta: "Tenaz", pista: "El que insiste una y otra vez y no afloja nunca." },
      { respuesta: "Tugurio", pista: "Vivienda o local miserable, sucio y de mala fama." },
      { respuesta: "Tañer", pista: "Hacer sonar una campana o un instrumento de cuerda." },
      { respuesta: "Templanza", pista: "Moderación y dominio de uno mismo frente a los excesos." },
    ],
  },
  U: {
    facil: [
      { respuesta: "Uva", pista: "Fruta chica y redonda con la que se hace el vino." },
      { respuesta: "Uña", pista: "Lámina dura que crece en la punta de los dedos." },
      { respuesta: "Uno", pista: "El primero de todos los números." },
      { respuesta: "Último", pista: "El que va al final de todos." },
      { respuesta: "Universidad", pista: "Donde se estudia una carrera después del secundario." },
      { respuesta: "Uruguay", pista: "País vecino que queda cruzando el río." },
      { respuesta: "Untar", pista: "Extender manteca o dulce sobre el pan." },
      { respuesta: "Usar", pista: "Emplear algo para lo que sirve." },
    ],
    medio: [
      { respuesta: "Uniforme", pista: "Ropa igual que llevan todos los miembros de un grupo." },
      { respuesta: "Urna", pista: "Recipiente cerrado donde se depositan los votos." },
      { respuesta: "Universo", pista: "Todo lo que existe: galaxias, estrellas y el espacio entre ellas." },
      { respuesta: "Ubicación", pista: "Lugar exacto en el que está algo." },
      { respuesta: "Urgencia", pista: "Necesidad de resolver algo en este mismo momento." },
      { respuesta: "Utensilio", pista: "Herramienta de cocina o de trabajo manual." },
      { respuesta: "Usina", pista: "Planta donde se genera la energía eléctrica." },
      { respuesta: "Unánime", pista: "Cuando absolutamente todos opinan lo mismo." },
    ],
    dificil: [
      { respuesta: "Umbral", pista: "Parte baja de la puerta que se pisa al entrar; también el punto donde algo empieza." },
      { respuesta: "Utopía", pista: "Sociedad perfecta que se imagina sabiendo que no se puede alcanzar." },
      { respuesta: "Ultimátum", pista: "Condición final que se impone antes de romper toda negociación." },
      { respuesta: "Ufano", pista: "Satisfecho y orgulloso de sí mismo, y que lo hace notar." },
      { respuesta: "Usura", pista: "Cobro de intereses abusivos por prestar plata." },
      { respuesta: "Urdimbre", pista: "Conjunto de hilos a lo largo de un tejido; también una trama oculta." },
      { respuesta: "Ubérrimo", pista: "Extremadamente fértil y abundante." },
      { respuesta: "Ultraje", pista: "Ofensa grave que humilla a alguien delante de todos." },
    ],
  },
  V: {
    facil: [
      { respuesta: "Vaca", pista: "Animal de campo que da leche." },
      { respuesta: "Ventana", pista: "Abertura en la pared por donde entra la luz." },
      { respuesta: "Vino", pista: "Bebida alcohólica que se hace con uvas." },
      { respuesta: "Verde", pista: "Color del pasto y de las hojas en primavera." },
      { respuesta: "Vaso", pista: "Recipiente del que se toma el agua." },
      { respuesta: "Viernes", pista: "Día con el que arranca el fin de semana." },
      { respuesta: "Viejo", pista: "El que ya tiene muchos años encima." },
      { respuesta: "Volar", pista: "Lo que hacen los pájaros y los aviones." },
    ],
    medio: [
      { respuesta: "Volcán", pista: "Montaña por cuyo cráter puede salir lava." },
      { respuesta: "Ventilador", pista: "Aparato de aspas que mueve el aire para refrescar." },
      { respuesta: "Vacuna", pista: "Preparado que genera defensas contra una enfermedad." },
      { respuesta: "Vela", pista: "Cilindro de cera con mecha; también la lona que empuja al barco." },
      { respuesta: "Veneno", pista: "Sustancia que enferma o mata al que la ingiere." },
      { respuesta: "Violín", pista: "Instrumento de cuatro cuerdas que se toca con un arco." },
      { respuesta: "Valija", pista: "Bolso rígido con el que se viaja." },
      { respuesta: "Vereda", pista: "Franja de la calle por donde caminan los peatones." },
    ],
    dificil: [
      { respuesta: "Vestigio", pista: "Resto que sobrevive de algo que ya desapareció." },
      { respuesta: "Vórtice", pista: "Centro de un remolino, donde todo gira y es absorbido." },
      { respuesta: "Vaivén", pista: "Movimiento continuo de ida y vuelta." },
      { respuesta: "Verdugo", pista: "El encargado de ejecutar la pena de muerte." },
      { respuesta: "Vértigo", pista: "Sensación de que todo gira, típica de quien mira desde muy alto." },
      { respuesta: "Vituperio", pista: "Insulto o reproche dicho en público." },
      { respuesta: "Vorágine", pista: "Remolino violento; también una actividad caótica que te arrastra." },
      { respuesta: "Veleidad", pista: "Capricho pasajero propio de quien no sostiene ninguna decisión." },
    ],
  },
  W: {
    facil: [
      { respuesta: "Wifi", pista: "Conexión a internet sin cables." },
      { respuesta: "Whisky", pista: "Bebida destilada de cereales que suele tomarse con hielo." },
      { respuesta: "Web", pista: "Red mundial de páginas enlazadas a la que se entra con un navegador." },
      { respuesta: "Wasabi", pista: "Pasta verde y picante que acompaña al sushi." },
      { respuesta: "Waffle", pista: "Masa dulce con cuadraditos que se come con dulce de leche." },
      { respuesta: "WhatsApp", pista: "Aplicación con la que se mandan mensajes desde el celular." },
      { respuesta: "Webcam", pista: "Cámara chica que va arriba de la pantalla." },
      { respuesta: "Windsurf", pista: "Deporte de tabla con vela sobre el agua." },
    ],
    medio: [
      { respuesta: "Wok", pista: "Sartén honda y redonda, típica de la cocina china." },
      { respuesta: "Western", pista: "Género de películas de vaqueros del lejano oeste." },
      { respuesta: "Waterpolo", pista: "Deporte de equipo que se juega dentro de la pileta con una pelota." },
      { respuesta: "Walkman", pista: "Reproductor portátil de casetes, ícono de los años ochenta." },
      { respuesta: "Waflera", pista: "Aparato de placas cuadriculadas con el que se hacen los waffles." },
      { respuesta: "Webinar", pista: "Charla o curso que se dicta por internet en vivo." },
    ],
    dificil: [
      { respuesta: "Watt", pista: "Unidad con la que se mide la potencia eléctrica." },
      { respuesta: "Wolframio", pista: "Metal durísimo de los filamentos de las lámparas, también llamado tungsteno." },
      { respuesta: "Wombat", pista: "Marsupial australiano robusto y de patas cortas que cava túneles." },
      { respuesta: "Wéber", pista: "Unidad con la que se mide el flujo magnético." },
    ],
  },
  X: {
    facil: [
      { respuesta: "Xilofón", pista: "Instrumento de láminas afinadas que se golpea con dos martillitos." },
    ],
    medio: [
      { respuesta: "Xenofobia", pista: "Rechazo u odio hacia los extranjeros." },
      { respuesta: "Xilografía", pista: "Técnica de grabado que consiste en tallar sobre una plancha de madera." },
      { respuesta: "Xenófobo", pista: "El que rechaza al extranjero solo por serlo." },
    ],
    dificil: [
      { respuesta: "Xerografía", pista: "Procedimiento de copia en seco: el principio de la fotocopiadora." },
      { respuesta: "Xilófago", pista: "Insecto que se alimenta de madera, como la termita." },
      { respuesta: "Xenón", pista: "Gas noble usado en faros de auto y en lámparas de gran potencia." },
      { respuesta: "Xerocopia", pista: "El nombre técnico de una fotocopia." },
      { respuesta: "Xilema", pista: "Tejido por el que la planta sube el agua desde la raíz." },
    ],
  },
  Y: {
    facil: [
      { respuesta: "Yogur", pista: "Alimento cremoso que se obtiene fermentando la leche." },
      { respuesta: "Yate", pista: "Embarcación de lujo para pasear por el mar." },
      { respuesta: "Yema", pista: "Parte amarilla del huevo." },
      { respuesta: "Yerba", pista: "Lo que se carga en el mate." },
      { respuesta: "Yoga", pista: "Disciplina de posturas y respiración que relaja el cuerpo." },
      { respuesta: "Yacaré", pista: "Reptil del litoral parecido al cocodrilo." },
      { respuesta: "Yuyo", pista: "Hierba silvestre que crece donde nadie la plantó." },
      { respuesta: "Yeso", pista: "Polvo blanco que endurece con agua y se usa para inmovilizar fracturas." },
    ],
    medio: [
      { respuesta: "Yunque", pista: "Bloque de hierro sobre el que el herrero golpea el metal al rojo." },
      { respuesta: "Yegua", pista: "Hembra del caballo, la madre del potrillo." },
      { respuesta: "Yodo", pista: "Sustancia marrón que se pone sobre las heridas para desinfectar." },
      { respuesta: "Yugular", pista: "Vena gruesa del cuello que lleva la sangre de vuelta al corazón." },
      { respuesta: "Yuca", pista: "Raíz comestible tropical con la que se hace harina." },
      { respuesta: "Yacimiento", pista: "Lugar donde se encuentra acumulado un mineral o restos arqueológicos." },
    ],
    dificil: [
      { respuesta: "Yugo", pista: "Madero que une a dos bueyes por la cabeza; también un dominio opresivo." },
      { respuesta: "Yermo", pista: "Terreno sin cultivar, deshabitado y estéril." },
      { respuesta: "Yelmo", pista: "Casco que cubría la cabeza del caballero medieval." },
      { respuesta: "Yerro", pista: "Error o equivocación cometida por descuido." },
      { respuesta: "Yuxtaponer", pista: "Poner dos cosas una al lado de la otra sin llegar a unirlas." },
      { respuesta: "Yacente", pista: "El que está acostado o tendido, como ciertas estatuas de tumbas." },
    ],
  },
  Z: {
    facil: [
      { respuesta: "Zapato", pista: "Calzado que cubre y protege el pie." },
      { respuesta: "Zanahoria", pista: "Verdura naranja y alargada, la preferida de los conejos." },
      { respuesta: "Zorro", pista: "Mamífero de cola peluda con fama de astuto." },
      { respuesta: "Zapatilla", pista: "Calzado deportivo de suela de goma." },
      { respuesta: "Zoológico", pista: "Lugar donde se exhiben animales de todo el mundo." },
      { respuesta: "Zona", pista: "Parte delimitada de un territorio." },
      { respuesta: "Zafar", pista: "Salir de un problema justito y sin consecuencias." },
      { respuesta: "Zumbido", pista: "Ruido continuo y molesto, como el del mosquito en la oreja." },
    ],
    medio: [
      { respuesta: "Zurdo", pista: "El que usa con preferencia la mano izquierda." },
      { respuesta: "Zanja", pista: "Excavación larga y angosta hecha en la tierra." },
      { respuesta: "Zarza", pista: "Arbusto espinoso de frutos oscuros." },
      { respuesta: "Zueco", pista: "Calzado de madera hecho de una sola pieza." },
      { respuesta: "Zorzal", pista: "Pájaro cantor muy común en los parques y jardines." },
      { respuesta: "Zambullida", pista: "Salto de cabeza al agua." },
      { respuesta: "Zíper", pista: "Cierre de dientes metálicos que se corre para abrir la campera." },
      { respuesta: "Zurcir", pista: "Coser un agujero de la ropa cruzando hilos hasta taparlo." },
    ],
    dificil: [
      { respuesta: "Zócalo", pista: "Franja inferior de la pared, tratada distinto del resto." },
      { respuesta: "Zarpar", pista: "Salir un barco del puerto para comenzar la travesía." },
      { respuesta: "Zaguán", pista: "Espacio cubierto en la entrada de una casa, antes de llegar al patio." },
      { respuesta: "Zozobra", pista: "Inquietud y angustia ante un peligro que se siente venir." },
      { respuesta: "Zafiro", pista: "Piedra preciosa de un azul intenso." },
      { respuesta: "Zigzag", pista: "Línea que avanza quebrándose de un lado al otro." },
      { respuesta: "Zalamero", pista: "El que halaga en exceso para conseguir algo." },
      { respuesta: "Zurrón", pista: "Bolsa de cuero que llevaba colgada el pastor." },
    ],
  },
};
